DROP TABLE rule_tree;
CREATE TABLE rule_tree ( id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID', treeName varchar(64) COMMENT '规则树Id', treeDesc varchar(128) COMMENT '规则树描述', treeRootNodeId bigint COMMENT '规则树根ID', createTime datetime COMMENT '创建时间', updateTime datetime COMMENT '更新时间', PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
insert into rule_tree (id, treeName, treeDesc, treeRootNodeId, createTime, updateTime) values (10001, '购物分类规则树', '用于分类不同类型用户可购物范围', 1, '0201-10-19 12:13:00', '0201-10-19 12:13:00');
DROP TABLE rule_tree_config;
CREATE TABLE rule_tree_config ( id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID', ruleKey varchar(16) COMMENT '规则Key', ruleDesc varchar(32) COMMENT '规则描述', limitType int(2) COMMENT '限定类型；1:=;2:>;3:<;4:>=;5<=;6:enum[枚举范围]', limitMode int(2) COMMENT '限制模式 1单选框、2多选框、3日期单录框、4日期范围框、5输入框', permitValue varchar(128) COMMENT '限定值', createTime datetime COMMENT '创建时间', updateTime datetime COMMENT '更新时间', PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE rule_tree_node;
CREATE TABLE rule_tree_node ( id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID', treeId int(2) COMMENT '规则树ID', nodeType int(2) COMMENT '节点类型；1子叶、2果实', nodeValue varchar(32) COMMENT '节点值[nodeType=2]；果实值', ruleKey varchar(16) COMMENT '规则Key', ruleDesc varchar(32) COMMENT '规则描述', PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
insert into rule_tree_node (id, treeId, nodeType, nodeValue, ruleKey, ruleDesc) values (1, 10001, 1, null, 'userGender', '用户性别[男/女]');
insert into rule_tree_node (id, treeId, nodeType, nodeValue, ruleKey, ruleDesc) values (11, 10001, 1, null, 'userAge', '用户年龄');
insert into rule_tree_node (id, treeId, nodeType, nodeValue, ruleKey, ruleDesc) values (12, 10001, 1, null, 'userAge', '用户年龄');
insert into rule_tree_node (id, treeId, nodeType, nodeValue, ruleKey, ruleDesc) values (111, 10001, 2, '果实A', null, null);
insert into rule_tree_node (id, treeId, nodeType, nodeValue, ruleKey, ruleDesc) values (112, 10001, 2, '果实B', null, null);
insert into rule_tree_node (id, treeId, nodeType, nodeValue, ruleKey, ruleDesc) values (121, 10001, 2, '果实C', null, null);
insert into rule_tree_node (id, treeId, nodeType, nodeValue, ruleKey, ruleDesc) values (122, 10001, 2, '果实D', null, null);
DROP TABLE rule_tree_node_line;
CREATE TABLE rule_tree_node_line ( id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID', treeId bigint COMMENT '规则树ID', nodeIdFrom bigint COMMENT '节点From', nodeIdTo bigint COMMENT '节点To', ruleLimitType int(2) COMMENT '限定类型；1:=;2:>;3:<;4:>=;5<=;6:enum[枚举范围];7:果实', ruleLimitValue varchar(32) COMMENT '限定值', PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
insert into rule_tree_node_line (id, treeId, nodeIdFrom, nodeIdTo, ruleLimitType, ruleLimitValue) values (1, 10001, 1, 11, 1, 'man');
insert into rule_tree_node_line (id, treeId, nodeIdFrom, nodeIdTo, ruleLimitType, ruleLimitValue) values (2, 10001, 1, 12, 1, 'woman');
insert into rule_tree_node_line (id, treeId, nodeIdFrom, nodeIdTo, ruleLimitType, ruleLimitValue) values (3, 10001, 11, 111, 3, '25');
insert into rule_tree_node_line (id, treeId, nodeIdFrom, nodeIdTo, ruleLimitType, ruleLimitValue) values (4, 10001, 11, 112, 4, '25');
insert into rule_tree_node_line (id, treeId, nodeIdFrom, nodeIdTo, ruleLimitType, ruleLimitValue) values (5, 10001, 12, 121, 3, '25');
insert into rule_tree_node_line (id, treeId, nodeIdFrom, nodeIdTo, ruleLimitType, ruleLimitValue) values (6, 10001, 12, 122, 4, '25');
